name: rudo_app_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.0.2
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  jwt_decode: ^0.3.1
  flutter_secure_storage: ^8.0.0
  dio: ^5.1.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  avatar_stack: ^1.2.0
  reactive_forms: ^14.1.0
  geolocator: ^9.0.2
  rxdart: ^0.27.7
  collection: ^1.17.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 

  fonts:
    - family: RaptorV3
      fonts:
        - asset: assets/fonts/raptor/RaptorV3Premium-Regular.otf
        - asset: assets/fonts/raptor/RaptorV3Premium-Bold.otf
          weight: 700
        - asset: assets/fonts/raptor/RaptorV3Premium-Semibold.otf
          weight: 600
        - asset: assets/fonts/raptor/RaptorV3Premium-Medium.otf
          weight: 500
        - asset: assets/fonts/raptor/RaptorV3Premium-Light.otf
          weight: 400
  
  assets:
    - 'assets/images/ic-google.png'
    - 'assets/images/logo-rudo.png'
    - 'assets/images/warning.png'
    - 'assets/images/festivity.png'
    - 'assets/images/medical.png'
    - 'assets/images/empty_events.png'
    - 'assets/images/empty_alerts.png'
    - 'assets/images/green_check.png'
    - 'assets/images/red_calendar.png'
    - 'assets/images/red_clock.png'
    - 'assets/images/red_cross.png'
    - 'assets/images/yellow_interrogant.png'
    - 'assets/images/temp.png'
    - 'assets/images/error.png'
    - 'assets/images/location_icon.png'
    - 'assets/images/notification_icon.png'
    - 'assets/images/person_icon.png'
