name: rudo_app_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.0.2
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  jwt_decode: ^0.3.1
  flutter_secure_storage: ^8.0.0
  dio: ^5.1.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  avatar_stack: ^1.2.0
  reactive_forms: ^14.1.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 
  
  assets:
    - 'assets/images/ic-google.png'
    - 'assets/images/logo-rudo.png'
