// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxNkNl0gbn_ECKNKJUqINg9Urh4t2I8D8',
    appId: '1:772525677602:android:83657f92ceb00c8c293e7b',
    messagingSenderId: '772525677602',
    projectId: 'rudo-app-clone',
    storageBucket: 'rudo-app-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU0r80BwDeXQjRkUKAnPHcjmREth2gZUg',
    appId: '1:772525677602:ios:edcf196544581fae293e7b',
    messagingSenderId: '772525677602',
    projectId: 'rudo-app-clone',
    storageBucket: 'rudo-app-clone.appspot.com',
    androidClientId: '772525677602-q4as2dhbdkich09mj886cvnj908ablii.apps.googleusercontent.com',
    iosClientId: '772525677602-70757reu7qvg24e5u4emdec3he5qnl42.apps.googleusercontent.com',
    iosBundleId: 'com.example.rudoAppClone',
  );
}
